apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - deployment.yaml
  - service.yaml
  - persistentvolumeclaim.yaml

commonLabels:
  app: pyroscope
  component: profiling

configMapGenerator:
  - name: pyroscope-config
    files:
    - ./config/pyroscope.yaml
    options:
      disableNameSuffixHash: true

