apiVersion: v1
kind: Service
metadata:
  labels:
    name: pyroscope
  name: pyroscope
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4040
      targetPort: 4040
  selector:
    name: pyroscope

